import type { Engine } from "@/components/engine-card/types";

export const ENGINES: Engine[] = [
  {
    id: "01",
    name: "Role Validation",
    tone: "default",
    tag: "Validation Engine",
    exec: {
      what: "Confirms hiring activity is real before outreach begins.",
      how: "Cross-validates ATS systems, job ecosystems, and external hiring signals.",
      input: "Company, market, role type, or hiring segment.",
    },
    depth: {
      kind: "terminal",
      title: "Active validation · 9 sources",
      sources: [
        { code: "GH", name: "Greenhouse", live: true },
        { code: "LV", name: "Lever" },
        { code: "WD", name: "Workday", live: true },
        { code: "SR", name: "SmartRecruiters" },
        { code: "LI", name: "LinkedIn Jobs", live: true },
        { code: "AS", name: "Ashby" },
        { code: "BH", name: "BambooHR" },
        { code: "CP", name: "Career Page" },
        { code: "IN", name: "Indeed" },
        { code: "+2", name: "2 internal", more: true },
      ],
      telemetry: [
        { k: "queries/s", v: "142", live: true },
        { k: "sources", v: "9" },
        { k: "confidence", v: "88%" },
        { k: "latency", v: "4s" },
      ],
      lines: [
        { t: "08:14:02", src: "GREENHOUSE", msg: "Sr. Account Executive · posted 6d ago", v: "OK", cls: "ok" },
        { t: "08:14:02", src: "LEVER", msg: "duplicate role surfaced from cross-post", v: "DUP", cls: "dup" },
        { t: "08:14:03", src: "WORKDAY", msg: "Director, Sales · 21d open · 2 reqs", v: "OK", cls: "ok" },
        { t: "08:14:03", src: "SMARTRECRUIT.", msg: "role pulled 11h ago — flag stale", v: "STALE", cls: "flag" },
        { t: "08:14:04", src: "LINKEDIN/JOBS", msg: "AE · NYC · 4d open · 32 applicants", v: "OK", cls: "ok" },
        { t: "08:14:04", src: "ASHBY", msg: "role aging > 45d · downgrade confidence", v: "AGED", cls: "flag" },
        { t: "08:14:05", src: "BAMBOOHR", msg: "internal mobility detected — confirm req active", v: "CONFIRM", cls: "flag" },
        { t: "08:14:05", src: "CAREER PAGE", msg: "role present on canonical careers feed", v: "OK", cls: "ok" },
        { t: "08:14:06", src: "INDEED", msg: "aggregator-only · ignore for canonical count", v: "SKIP", cls: "dup" },
        { t: "08:14:06", src: "GREENHOUSE", msg: "salary band published · senior tier", v: "OK", cls: "ok" },
        { t: "08:14:07", src: "WORKDAY", msg: "hiring manager identified · VP Sales", v: "OK", cls: "ok" },
        { t: "08:14:07", src: "LINKEDIN/JOBS", msg: "cross-post detected on partner ATS · dedupe", v: "DUP", cls: "dup" },
        { t: "08:14:08", src: "ASHBY", msg: "job description fingerprint matches Greenhouse", v: "MERGE", cls: "flag" },
        { t: "08:14:08", src: "CAREER PAGE", msg: "meta tag verified · canonical req confirmed", v: "OK", cls: "ok" },
        { t: "08:14:09", src: "CONSENSUS", msg: "4 sources agree · confidence raised", v: "●●●●", cls: "ok" },
      ],
    },
    audit: {
      summary:
        "4 independent sources confirm the role is active and fresh. 1 duplicate filtered, 2 stale postings downgraded. Confidence raised to ●●●● on consensus.",
      meta: "124 validated · 7 sources · 4s avg",
      cols: "1.4fr 1.5fr 0.9fr 0.6fr",
      head: ["Company", "Role", "Confidence", "Days"],
      rows: [
        ["Atlas Therapeutics", "Sr. Account Executive", "conf:4", "6d"],
        ["[Company A]", "[Role · Director, Sales]", "conf:4", "21d"],
        ["[Company B]", "[Role · AE, Mid-Market]", "conf:3", "11d"],
      ],
    },
    handoff: {
      nextId: "02",
      nextName: "Buying Signals",
      variables: 5,
      json: {
        entity_name: "Atlas Therapeutics",
        role: "Sr. Account Executive",
        role_age_days: 6,
        confidence: 4,
        sources_verified: ["greenhouse", "workday", "linkedin", "career_page"],
      },
    },
  },
  {
    id: "02",
    name: "Buying Signals",
    tone: "amber",
    tag: "Multi-Vertical Intelligence",
    exec: {
      what: "Detects accounts showing measurable intent to buy right now.",
      how: "Aggregates external buying signals — funding, leadership, expansion, M&A, product moves — and scores recency × density × correlation.",
      input: "Validated companies from Engine 01.",
    },
    depth: {
      kind: "terminal",
      title: "Signal stream · 8 verticals",
      sources: [
        { code: "FW", name: "Funding wires", live: true },
        { code: "CB", name: "Crunchbase", live: true },
        { code: "PB", name: "Pitchbook" },
        { code: "LI", name: "LinkedIn", live: true },
        { code: "BI", name: "BuiltIn" },
        { code: "TC", name: "Tech press" },
        { code: "SE", name: "SEC filings" },
        { code: "EC", name: "Earnings calls" },
        { code: "+3", name: "3 internal", more: true },
      ],
      telemetry: [
        { k: "signals/min", v: "47", live: true },
        { k: "density", v: "●●●●●" },
        { k: "correlation", v: "HIGH" },
        { k: "window", v: "14d" },
      ],
      lines: [
        { t: "08:21:14", src: "FUNDING", msg: "Series C · $42M · 3d ago", v: "+34", cls: "flag" },
        { t: "08:21:15", src: "LEADERSHIP", msg: "VP Sales hired · 11d ago · public announcement", v: "+22", cls: "flag" },
        { t: "08:21:15", src: "EXPANSION", msg: "NYC office posted · 60 seats · 5d ago", v: "+18", cls: "flag" },
        { t: "08:21:16", src: "M&A", msg: "acquired competitor · integration headcount up", v: "+28", cls: "flag" },
        { t: "08:21:16", src: "PRODUCT", msg: "launched enterprise tier · go-to-market push", v: "+14", cls: "flag" },
        { t: "08:21:17", src: "EXEC MOVES", msg: "CRO ex-Datadog · joined 30d ago", v: "+19", cls: "flag" },
        { t: "08:21:17", src: "PARTNERSHIPS", msg: "new channel deal · pipeline expansion signal", v: "+12", cls: "flag" },
        { t: "08:21:18", src: "SEC FILING", msg: "10-Q referenced GTM acceleration · 2 mentions", v: "+8", cls: "flag" },
        { t: "08:21:18", src: "CRUNCHBASE", msg: "investor tier verified · growth-stage signal", v: "OK", cls: "ok" },
        { t: "08:21:19", src: "DENSITY", msg: "4 signals in 30d · cluster detected", v: "●●●●●", cls: "ok" },
        { t: "08:21:19", src: "CORRELATION", msg: "funding + leadership + expansion · high", v: "HIGH", cls: "ok" },
        { t: "08:21:20", src: "NORTHPOINT", msg: "composite score raised · priority lane", v: "PRI:1", cls: "ok" },
      ],
    },
    audit: {
      summary:
        "Density cluster detected — 4 high-recency signals in 30 days, correlated across funding, leadership and expansion. Strongest window opens for the next 14 days.",
      meta: "38 accounts · density-ranked · 30d window",
      cols: "1.4fr 1.6fr 0.7fr 0.8fr",
      head: ["Company", "Why Now", "Strength", "Window"],
      rows: [
        ["Northpoint Logistics", "Series C + VP Sales hire", "conf:5", "14d"],
        ["[Company E]", "Funding + expansion", "conf:4", "21d"],
        ["[Company F]", "M&A + integration headcount", "conf:5", "7d"],
      ],
    },
    handoff: {
      nextId: "03",
      nextName: "Stakeholder Mapping",
      variables: 5,
      json: {
        entity_name: "Northpoint Logistics",
        primary_signal: "series_c_funding",
        signal_strength: 5,
        signal_window_days: 14,
        correlated_signals: ["vp_sales_hire", "nyc_expansion"],
      },
    },
  },
  {
    id: "03",
    name: "Stakeholder Mapping",
    tone: "default",
    tag: "Intelligence Engine",
    exec: {
      what: "Identifies the right humans inside each qualified account.",
      how: "Maps reporting structures, tenure, decision authority, and influence — surfaces both the visible and quiet decision-makers.",
      input: "Signal-verified accounts from Engine 02.",
    },
    depth: {
      kind: "nodes",
      title: "Active map · Northpoint Logistics",
      sources: [
        { code: "LI", name: "LinkedIn", live: true },
        { code: "AP", name: "Apollo", live: true },
        { code: "ZI", name: "ZoomInfo" },
        { code: "LU", name: "Lusha" },
        { code: "OC", name: "Org-chart infer" },
        { code: "CR", name: "Internal CRM" },
        { code: "PW", name: "Press wires" },
        { code: "+1", name: "1 enrichment", more: true },
      ],
      telemetry: [
        { k: "profiles", v: "142", live: true },
        { k: "mapped", v: "47" },
        { k: "confidence", v: "91%" },
        { k: "paths", v: "12" },
      ],
      legend: ["Lead stakeholder", "Influencer"],
      nodes: [
        { x: 50, y: 18, lbl: "CRO", role: "Decision · joined 30d ago", lead: true, d: 0 },
        { x: 22, y: 42, lbl: "VP SALES", role: "New hire · 11d", d: 220 },
        { x: 78, y: 42, lbl: "VP RevOps", role: "Tenured · 4y", d: 280 },
        { x: 14, y: 72, lbl: "DIR · AE", role: "Hiring lead", d: 460 },
        { x: 40, y: 76, lbl: "DIR · SE", role: "Cross-functional", d: 520 },
        { x: 64, y: 76, lbl: "DIR · Ops", role: "Budget influence", d: 580 },
        { x: 88, y: 72, lbl: "CHIEF·STAFF", role: "Quiet authority", d: 640 },
      ],
      edges: [
        [0, 1],
        [0, 2],
        [1, 3],
        [1, 4],
        [2, 5],
        [2, 6],
      ],
    },
    audit: {
      summary:
        "CRO identified as primary decision-maker — new to role, inheriting GTM build authority. VP RevOps mapped as enterprise champion. Chief of Staff flagged as quiet path.",
      meta: "38 accounts · 142 stakeholders · authority-ranked",
      cols: "1.3fr 1fr 0.8fr 0.7fr",
      head: ["Stakeholder", "Role", "Authority", "Path"],
      rows: [
        ["Daniela Hart", "CRO · Northpoint", "conf:5", "Direct"],
        ["[Stakeholder]", "[VP Sales · new hire]", "conf:4", "Direct"],
        ["[Stakeholder]", "[Chief of Staff]", "conf:3", "Quiet"],
      ],
    },
    handoff: {
      nextId: "04",
      nextName: "Outreach Architecture",
      variables: 5,
      json: {
        key_persona: "Daniela Hart",
        persona_role: "CRO",
        authority_score: 5,
        access_path: "direct",
        supporting_personas: ["vp_revops", "chief_of_staff"],
      },
    },
  },
  {
    id: "04",
    name: "Outreach Architecture",
    tone: "default",
    tag: "Synthesis Engine",
    exec: {
      what: "Constructs the right message for the right person at the right moment.",
      how: "Synthesizes intelligence into context-anchored outreach — tone, signal anchor, pain hypothesis, value frame, and channel.",
      input: "Mapped stakeholders from Engine 03.",
    },
    depth: {
      kind: "panels",
      title: "Synthesis in progress",
      sources: [
        { code: "RD", name: "Reddit signals", live: true },
        { code: "TW", name: "X / Twitter", live: true },
        { code: "GD", name: "Glassdoor" },
        { code: "RV", name: "RepVue" },
        { code: "EC", name: "Earnings calls" },
        { code: "IS", name: "Industry Slack" },
        { code: "PR", name: "PR Newswire" },
        { code: "+2", name: "2 internal", more: true },
      ],
      telemetry: [
        { k: "tones", v: "8", live: true },
        { k: "anchors", v: "142" },
        { k: "channels", v: "4" },
        { k: "scaffolds", v: "142" },
      ],
      panels: [
        {
          lbl: "Tone Calibration",
          stat: "set",
          rows: [
            ["Register", "Operator → Operator"],
            ["Length", "92 words · 3 paragraphs"],
            ["Voice", "Concrete · specific · no hype"],
          ],
        },
        {
          lbl: "Signal Anchor",
          stat: "+34",
          rows: [
            ["Source", "Series C · 3d ago"],
            ["Reference", "VP Sales hire · 11d ago"],
            ["Framing", "congratulatory · not sycophantic"],
          ],
        },
        {
          lbl: "Pain Identification",
          stat: "pri:1",
          rows: [
            ["Inferred", "New CRO inheriting GTM build"],
            ["Tension", "integration headcount risk"],
            ["Hook", "how peers handled the same window"],
          ],
        },
        {
          lbl: "Channel Selection",
          stat: "email+li",
          rows: [
            ["Primary", "Email · CRO direct"],
            ["Secondary", "LinkedIn DM · 48h gap"],
            ["Fallback", "Warm intro · VP RevOps"],
          ],
        },
      ],
    },
    audit: {
      summary:
        "Operator-to-operator register chosen. Anchored on Series C + new-role inheritance. Pain hook: integration headcount risk. Channel: direct email to CRO, LinkedIn echo at 48h.",
      meta: "142 stakeholders · 1 scaffold each · context-anchored",
      cols: "1.1fr 0.7fr 1.5fr 0.6fr",
      head: ["Stakeholder", "Channel", "Anchor", "Status"],
      rows: [
        ["Daniela Hart", "Email", "Series C + new role inheritance", "ok"],
        ["[Stakeholder]", "[Email]", "[Expansion · NYC seats]", "ok"],
        ["[Stakeholder]", "[Intro]", "[Warm path · VP RevOps]", "ok"],
      ],
    },
    handoff: {
      nextId: "05",
      nextName: "Timing · Orchestration",
      variables: 5,
      json: {
        key_persona: "Daniela Hart",
        channel: "email",
        anchor: "series_c_new_role_inheritance",
        message_id: "msg_a8f1c2",
        sequence_priority: 1,
      },
    },
  },
  {
    id: "05",
    name: "Timing · Orchestration",
    tone: "default",
    tag: "Orchestration Engine",
    exec: {
      what: "Sequences outreach for maximum signal-window coverage without noise.",
      how: "Coordinates touchpoints across channels, time-zones, signal recency, and response state.",
      input: "Outreach scaffolds from Engine 04.",
    },
    depth: {
      kind: "panels",
      title: "Sequencer · 142 active",
      sources: [
        { code: "BH", name: "Bullhorn", live: true },
        { code: "SF", name: "Salesforce" },
        { code: "HS", name: "HubSpot" },
        { code: "OR", name: "Outreach", live: true },
        { code: "SL", name: "SmartLead" },
        { code: "AP", name: "Apollo" },
        { code: "CL", name: "Calendly" },
        { code: "+2", name: "2 connectors", more: true },
      ],
      telemetry: [
        { k: "sequences", v: "142", live: true },
        { k: "channels", v: "4" },
        { k: "replies", v: "9" },
        { k: "meetings", v: "4" },
      ],
      panels: [
        {
          lbl: "Signal Window",
          stat: "14d",
          rows: [
            ["Account", "Northpoint · CRO"],
            ["Recency", "Funding · 3d · within window"],
            ["Decay", "half-life · 9d remaining"],
          ],
        },
        {
          lbl: "Touch Cadence",
          stat: "5-step",
          rows: [
            ["Day 0", "Email · primary anchor"],
            ["Day 2", "LinkedIn DM · soft echo"],
            ["Day 5", "Email · operator angle"],
            ["Day 9", "Warm intro · VP RevOps"],
          ],
        },
        {
          lbl: "Channel Routing",
          stat: "4 ch.",
          rows: [
            ["Email", "102 active"],
            ["LinkedIn", "64 active"],
            ["Intro", "12 in-flight"],
            ["Phone", "on-demand · CRO tier"],
          ],
        },
        {
          lbl: "Response State",
          stat: "live",
          rows: [
            ["Open", "38"],
            ["Reply", "9"],
            ["Meeting", "4"],
            ["Routed →", "Engine 06"],
          ],
        },
      ],
    },
    audit: {
      summary:
        "Sequence locked to 14-day signal window with 9-day half-life. 5-step cadence across 4 channels. Routing engine watches response state and re-prioritizes in real time.",
      meta: "142 sequences · 4 channels · signal-windowed",
      cols: "1.1fr 0.5fr 0.9fr 0.7fr",
      head: ["Stakeholder", "Day", "Channel", "Status"],
      rows: [
        ["Daniela Hart", "D2", "LinkedIn", "ok"],
        ["[Stakeholder]", "[D0]", "[Email]", "live"],
        ["[Stakeholder]", "[D5]", "[Email]", "ok"],
      ],
    },
    handoff: {
      nextId: "06",
      nextName: "Audit & Delivery",
      variables: 5,
      json: {
        sequence_id: "seq_n3p9_d27",
        persona: "Daniela Hart",
        current_step: 2,
        response_state: "open_no_reply",
        next_touch_at: "2026-03-27T13:00:00Z",
      },
    },
  },
  {
    id: "06",
    name: "Audit & Delivery",
    tone: "navy",
    tag: "Delivery Engine",
    exec: {
      what: "Wraps the workflow in a strategic audit and delivers verified opportunities to the operator's system of record.",
      how: "Consolidates every engine's reasoning into a single audit trail, then compresses delivery into Bullhorn / CRM as a clean opportunity package.",
      input: "Active sequences and engine outputs from Engines 01 – 05.",
    },
    depth: {
      kind: "panels",
      title: "Operator review · Northpoint · Daniela Hart",
      sources: [
        { code: "BH", name: "Bullhorn (write)", live: true },
        { code: "SL", name: "Slack alerts", live: true },
        { code: "AL", name: "Audit log", live: true },
        { code: "SR", name: "Source registry" },
        { code: "AC", name: "Access controls" },
        { code: "+2", name: "2 integrations", more: true },
      ],
      telemetry: [
        { k: "trails", v: "8", live: true },
        { k: "sources", v: "7" },
        { k: "audits", v: "142" },
        { k: "deliveries", v: "142" },
      ],
      panels: [
        {
          lbl: "Audit Trail",
          stat: "8 steps",
          rows: [
            ["Why account", "Series C · VP Sales · expansion · density 4"],
            ["Why person", "CRO · new · GTM rebuild authority"],
            ["Why now", "Signal window · 14d half-life"],
            ["Why channel", "Direct email · CRO-tier preference"],
          ],
        },
        {
          lbl: "Source Citations",
          stat: "7",
          rows: [
            ["Funding", "press release · 03-12-26"],
            ["Leadership", "LinkedIn announcement · 03-04-26"],
            ["Expansion", "careers feed · 60 seats · 03-10-26"],
            ["Authority", "org map · CRO scope inference"],
          ],
        },
        {
          lbl: "Delivery Package",
          stat: "ready",
          rows: [
            ["Opportunity", "opp_n3p9_d27"],
            ["Audit URL", "glve.it/audit/n3p9"],
            ["Payload", "verified · signed · auditable"],
            ["Destination", "Bullhorn · auto-routed"],
          ],
        },
        {
          lbl: "Operator Controls",
          stat: "live",
          rows: [
            ["Approve", "commit to Bullhorn"],
            ["Rewrite", "open scaffold · keep anchor"],
            ["Reroute", "switch to VP RevOps · warm intro"],
            ["Hold", "pause sequence · 7d"],
          ],
        },
      ],
    },
    audit: {
      summary:
        "Every engine's reasoning consolidated into a single audit trail — 8 reasoning steps, 7 source citations. Delivery package compressed and routed to Bullhorn. Operator retains override.",
      meta: "Auditable revenue motion · operator-overridable",
      cols: "1.2fr 1.4fr 0.6fr 0.8fr",
      head: ["Account", "Reasoning", "Sources", "Decision"],
      rows: [
        ["Atlas Therapeutics", "Hiring + density · 4-source consensus", "7", "sent"],
        ["[Account]", "[Funding + leadership window]", "6", "sent"],
        ["[Account]", "[Expansion + M&A correlation]", "5", "hold"],
      ],
    },
    handoff: {
      nextId: null,
      nextName: "Bullhorn · operator system of record",
      variables: 5,
      json: {
        opportunity_id: "opp_n3p9_d27",
        opportunity_summary: "CRO · series_c_window · 14d",
        audit_url: "glve.it/audit/n3p9",
        action_payload: "verified · signed · ready",
        delivery_channel: "bullhorn_api",
      },
      finalLabel: "DELIVERY · White Glove · routed to operator",
    },
  },
];
